/*
 * This file is generated by jOOQ.
 */
package com.restapi.jooq.model.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BpCompartmentAllocation implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long       id;
    private Long       orderId;
    private Long       journeyId;
    private BigDecimal weight;
    private String     source;
    private String     destination;
    private String     fuelType;

    public BpCompartmentAllocation() {}

    public BpCompartmentAllocation(BpCompartmentAllocation value) {
        this.id = value.id;
        this.orderId = value.orderId;
        this.journeyId = value.journeyId;
        this.weight = value.weight;
        this.source = value.source;
        this.destination = value.destination;
        this.fuelType = value.fuelType;
    }

    public BpCompartmentAllocation(
        Long       id,
        Long       orderId,
        Long       journeyId,
        BigDecimal weight,
        String     source,
        String     destination,
        String     fuelType
    ) {
        this.id = id;
        this.orderId = orderId;
        this.journeyId = journeyId;
        this.weight = weight;
        this.source = source;
        this.destination = destination;
        this.fuelType = fuelType;
    }

    /**
     * Getter for <code>public.bp_compartment_allocation.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.bp_compartment_allocation.id</code>.
     */
    public BpCompartmentAllocation setId(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.bp_compartment_allocation.order_id</code>.
     */
    public Long getOrderId() {
        return this.orderId;
    }

    /**
     * Setter for <code>public.bp_compartment_allocation.order_id</code>.
     */
    public BpCompartmentAllocation setOrderId(Long orderId) {
        this.orderId = orderId;
        return this;
    }

    /**
     * Getter for <code>public.bp_compartment_allocation.journey_id</code>.
     */
    public Long getJourneyId() {
        return this.journeyId;
    }

    /**
     * Setter for <code>public.bp_compartment_allocation.journey_id</code>.
     */
    public BpCompartmentAllocation setJourneyId(Long journeyId) {
        this.journeyId = journeyId;
        return this;
    }

    /**
     * Getter for <code>public.bp_compartment_allocation.weight</code>.
     */
    public BigDecimal getWeight() {
        return this.weight;
    }

    /**
     * Setter for <code>public.bp_compartment_allocation.weight</code>.
     */
    public BpCompartmentAllocation setWeight(BigDecimal weight) {
        this.weight = weight;
        return this;
    }

    /**
     * Getter for <code>public.bp_compartment_allocation.source</code>.
     */
    public String getSource() {
        return this.source;
    }

    /**
     * Setter for <code>public.bp_compartment_allocation.source</code>.
     */
    public BpCompartmentAllocation setSource(String source) {
        this.source = source;
        return this;
    }

    /**
     * Getter for <code>public.bp_compartment_allocation.destination</code>.
     */
    public String getDestination() {
        return this.destination;
    }

    /**
     * Setter for <code>public.bp_compartment_allocation.destination</code>.
     */
    public BpCompartmentAllocation setDestination(String destination) {
        this.destination = destination;
        return this;
    }

    /**
     * Getter for <code>public.bp_compartment_allocation.fuel_type</code>.
     */
    public String getFuelType() {
        return this.fuelType;
    }

    /**
     * Setter for <code>public.bp_compartment_allocation.fuel_type</code>.
     */
    public BpCompartmentAllocation setFuelType(String fuelType) {
        this.fuelType = fuelType;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final BpCompartmentAllocation other = (BpCompartmentAllocation) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (orderId == null) {
            if (other.orderId != null)
                return false;
        }
        else if (!orderId.equals(other.orderId))
            return false;
        if (journeyId == null) {
            if (other.journeyId != null)
                return false;
        }
        else if (!journeyId.equals(other.journeyId))
            return false;
        if (weight == null) {
            if (other.weight != null)
                return false;
        }
        else if (!weight.equals(other.weight))
            return false;
        if (source == null) {
            if (other.source != null)
                return false;
        }
        else if (!source.equals(other.source))
            return false;
        if (destination == null) {
            if (other.destination != null)
                return false;
        }
        else if (!destination.equals(other.destination))
            return false;
        if (fuelType == null) {
            if (other.fuelType != null)
                return false;
        }
        else if (!fuelType.equals(other.fuelType))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.orderId == null) ? 0 : this.orderId.hashCode());
        result = prime * result + ((this.journeyId == null) ? 0 : this.journeyId.hashCode());
        result = prime * result + ((this.weight == null) ? 0 : this.weight.hashCode());
        result = prime * result + ((this.source == null) ? 0 : this.source.hashCode());
        result = prime * result + ((this.destination == null) ? 0 : this.destination.hashCode());
        result = prime * result + ((this.fuelType == null) ? 0 : this.fuelType.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("BpCompartmentAllocation (");

        sb.append(id);
        sb.append(", ").append(orderId);
        sb.append(", ").append(journeyId);
        sb.append(", ").append(weight);
        sb.append(", ").append(source);
        sb.append(", ").append(destination);
        sb.append(", ").append(fuelType);

        sb.append(")");
        return sb.toString();
    }
}
