/*
 * This file is generated by jOOQ.
 */
package com.restapi.jooq.model.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BpJourneyLine implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Long journeyId;
    private Long compartmentId;

    public BpJourneyLine() {}

    public BpJourneyLine(BpJourneyLine value) {
        this.id = value.id;
        this.journeyId = value.journeyId;
        this.compartmentId = value.compartmentId;
    }

    public BpJourneyLine(
        Long id,
        Long journeyId,
        Long compartmentId
    ) {
        this.id = id;
        this.journeyId = journeyId;
        this.compartmentId = compartmentId;
    }

    /**
     * Getter for <code>public.bp_journey_line.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.bp_journey_line.id</code>.
     */
    public BpJourneyLine setId(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.bp_journey_line.journey_id</code>.
     */
    public Long getJourneyId() {
        return this.journeyId;
    }

    /**
     * Setter for <code>public.bp_journey_line.journey_id</code>.
     */
    public BpJourneyLine setJourneyId(Long journeyId) {
        this.journeyId = journeyId;
        return this;
    }

    /**
     * Getter for <code>public.bp_journey_line.compartment_id</code>.
     */
    public Long getCompartmentId() {
        return this.compartmentId;
    }

    /**
     * Setter for <code>public.bp_journey_line.compartment_id</code>.
     */
    public BpJourneyLine setCompartmentId(Long compartmentId) {
        this.compartmentId = compartmentId;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final BpJourneyLine other = (BpJourneyLine) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (journeyId == null) {
            if (other.journeyId != null)
                return false;
        }
        else if (!journeyId.equals(other.journeyId))
            return false;
        if (compartmentId == null) {
            if (other.compartmentId != null)
                return false;
        }
        else if (!compartmentId.equals(other.compartmentId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.journeyId == null) ? 0 : this.journeyId.hashCode());
        result = prime * result + ((this.compartmentId == null) ? 0 : this.compartmentId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("BpJourneyLine (");

        sb.append(id);
        sb.append(", ").append(journeyId);
        sb.append(", ").append(compartmentId);

        sb.append(")");
        return sb.toString();
    }
}
