/*
 * This file is generated by jOOQ.
 */
package com.restapi.jooq.model.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BpOrderLine implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long       id;
    private Long       orderId;
    private BigDecimal weight;
    private String     source;
    private String     destination;

    public BpOrderLine() {}

    public BpOrderLine(BpOrderLine value) {
        this.id = value.id;
        this.orderId = value.orderId;
        this.weight = value.weight;
        this.source = value.source;
        this.destination = value.destination;
    }

    public BpOrderLine(
        Long       id,
        Long       orderId,
        BigDecimal weight,
        String     source,
        String     destination
    ) {
        this.id = id;
        this.orderId = orderId;
        this.weight = weight;
        this.source = source;
        this.destination = destination;
    }

    /**
     * Getter for <code>public.bp_order_line.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.bp_order_line.id</code>.
     */
    public BpOrderLine setId(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.bp_order_line.order_id</code>.
     */
    public Long getOrderId() {
        return this.orderId;
    }

    /**
     * Setter for <code>public.bp_order_line.order_id</code>.
     */
    public BpOrderLine setOrderId(Long orderId) {
        this.orderId = orderId;
        return this;
    }

    /**
     * Getter for <code>public.bp_order_line.weight</code>.
     */
    public BigDecimal getWeight() {
        return this.weight;
    }

    /**
     * Setter for <code>public.bp_order_line.weight</code>.
     */
    public BpOrderLine setWeight(BigDecimal weight) {
        this.weight = weight;
        return this;
    }

    /**
     * Getter for <code>public.bp_order_line.source</code>.
     */
    public String getSource() {
        return this.source;
    }

    /**
     * Setter for <code>public.bp_order_line.source</code>.
     */
    public BpOrderLine setSource(String source) {
        this.source = source;
        return this;
    }

    /**
     * Getter for <code>public.bp_order_line.destination</code>.
     */
    public String getDestination() {
        return this.destination;
    }

    /**
     * Setter for <code>public.bp_order_line.destination</code>.
     */
    public BpOrderLine setDestination(String destination) {
        this.destination = destination;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final BpOrderLine other = (BpOrderLine) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (orderId == null) {
            if (other.orderId != null)
                return false;
        }
        else if (!orderId.equals(other.orderId))
            return false;
        if (weight == null) {
            if (other.weight != null)
                return false;
        }
        else if (!weight.equals(other.weight))
            return false;
        if (source == null) {
            if (other.source != null)
                return false;
        }
        else if (!source.equals(other.source))
            return false;
        if (destination == null) {
            if (other.destination != null)
                return false;
        }
        else if (!destination.equals(other.destination))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.orderId == null) ? 0 : this.orderId.hashCode());
        result = prime * result + ((this.weight == null) ? 0 : this.weight.hashCode());
        result = prime * result + ((this.source == null) ? 0 : this.source.hashCode());
        result = prime * result + ((this.destination == null) ? 0 : this.destination.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("BpOrderLine (");

        sb.append(id);
        sb.append(", ").append(orderId);
        sb.append(", ").append(weight);
        sb.append(", ").append(source);
        sb.append(", ").append(destination);

        sb.append(")");
        return sb.toString();
    }
}
