/*
 * This file is generated by jOOQ.
 */
package com.restapi.jooq.model;


import com.restapi.jooq.model.tables.BpCompartmentAllocation;
import com.restapi.jooq.model.tables.BpJourney;
import com.restapi.jooq.model.tables.BpJourneyLine;
import com.restapi.jooq.model.tables.BpOrder;
import com.restapi.jooq.model.tables.BpOrderLine;
import com.restapi.jooq.model.tables.Databasechangelog;
import com.restapi.jooq.model.tables.Databasechangeloglock;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.bp_compartment_allocation</code>.
     */
    public final BpCompartmentAllocation BP_COMPARTMENT_ALLOCATION = BpCompartmentAllocation.BP_COMPARTMENT_ALLOCATION;

    /**
     * The table <code>public.bp_journey</code>.
     */
    public final BpJourney BP_JOURNEY = BpJourney.BP_JOURNEY;

    /**
     * The table <code>public.bp_journey_line</code>.
     */
    public final BpJourneyLine BP_JOURNEY_LINE = BpJourneyLine.BP_JOURNEY_LINE;

    /**
     * The table <code>public.bp_order</code>.
     */
    public final BpOrder BP_ORDER = BpOrder.BP_ORDER;

    /**
     * The table <code>public.bp_order_line</code>.
     */
    public final BpOrderLine BP_ORDER_LINE = BpOrderLine.BP_ORDER_LINE;

    /**
     * The table <code>public.databasechangelog</code>.
     */
    public final Databasechangelog DATABASECHANGELOG = Databasechangelog.DATABASECHANGELOG;

    /**
     * The table <code>public.databasechangeloglock</code>.
     */
    public final Databasechangeloglock DATABASECHANGELOGLOCK = Databasechangeloglock.DATABASECHANGELOGLOCK;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        return Arrays.<Sequence<?>>asList(
            Sequences.BP_COMPARTMENT_ALLOCATION_ID_SEQ,
            Sequences.BP_JOURNEY_ID_SEQ,
            Sequences.BP_JOURNEY_LINE_ID_SEQ,
            Sequences.BP_ORDER_ID_SEQ,
            Sequences.BP_ORDER_LINE_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            BpCompartmentAllocation.BP_COMPARTMENT_ALLOCATION,
            BpJourney.BP_JOURNEY,
            BpJourneyLine.BP_JOURNEY_LINE,
            BpOrder.BP_ORDER,
            BpOrderLine.BP_ORDER_LINE,
            Databasechangelog.DATABASECHANGELOG,
            Databasechangeloglock.DATABASECHANGELOGLOCK);
    }
}
