/*
 * This file is generated by jOOQ.
 */
package com.restapi.jooq.model;


import com.restapi.jooq.model.tables.BpCompartmentAllocation;
import com.restapi.jooq.model.tables.BpJourney;
import com.restapi.jooq.model.tables.BpJourneyLine;
import com.restapi.jooq.model.tables.BpOrder;
import com.restapi.jooq.model.tables.BpOrderLine;
import com.restapi.jooq.model.tables.Databasechangelog;
import com.restapi.jooq.model.tables.Databasechangeloglock;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.bp_compartment_allocation</code>.
     */
    public static final BpCompartmentAllocation BP_COMPARTMENT_ALLOCATION = BpCompartmentAllocation.BP_COMPARTMENT_ALLOCATION;

    /**
     * The table <code>public.bp_journey</code>.
     */
    public static final BpJourney BP_JOURNEY = BpJourney.BP_JOURNEY;

    /**
     * The table <code>public.bp_journey_line</code>.
     */
    public static final BpJourneyLine BP_JOURNEY_LINE = BpJourneyLine.BP_JOURNEY_LINE;

    /**
     * The table <code>public.bp_order</code>.
     */
    public static final BpOrder BP_ORDER = BpOrder.BP_ORDER;

    /**
     * The table <code>public.bp_order_line</code>.
     */
    public static final BpOrderLine BP_ORDER_LINE = BpOrderLine.BP_ORDER_LINE;

    /**
     * The table <code>public.databasechangelog</code>.
     */
    public static final Databasechangelog DATABASECHANGELOG = Databasechangelog.DATABASECHANGELOG;

    /**
     * The table <code>public.databasechangeloglock</code>.
     */
    public static final Databasechangeloglock DATABASECHANGELOGLOCK = Databasechangeloglock.DATABASECHANGELOGLOCK;
}
