/*
 * This file is generated by jOOQ.
 */
package com.restapi.jooq.model.tables.records;


import com.restapi.jooq.model.tables.BpJourney;

import java.math.BigDecimal;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BpJourneyRecord extends UpdatableRecordImpl<BpJourneyRecord> implements Record7<Long, BigDecimal, Boolean, Long, Long, Long, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.bp_journey.id</code>.
     */
    public BpJourneyRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.bp_journey.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.bp_journey.allocation_ratio</code>.
     */
    public BpJourneyRecord setAllocationRatio(BigDecimal value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.bp_journey.allocation_ratio</code>.
     */
    public BigDecimal getAllocationRatio() {
        return (BigDecimal) get(1);
    }

    /**
     * Setter for <code>public.bp_journey.arranged</code>.
     */
    public BpJourneyRecord setArranged(Boolean value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.bp_journey.arranged</code>.
     */
    public Boolean getArranged() {
        return (Boolean) get(2);
    }

    /**
     * Setter for <code>public.bp_journey.container1</code>.
     */
    public BpJourneyRecord setContainer1(Long value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.bp_journey.container1</code>.
     */
    public Long getContainer1() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.bp_journey.container2</code>.
     */
    public BpJourneyRecord setContainer2(Long value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.bp_journey.container2</code>.
     */
    public Long getContainer2() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>public.bp_journey.contanier3</code>.
     */
    public BpJourneyRecord setContanier3(Long value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.bp_journey.contanier3</code>.
     */
    public Long getContanier3() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>public.bp_journey.contanier4</code>.
     */
    public BpJourneyRecord setContanier4(Long value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.bp_journey.contanier4</code>.
     */
    public Long getContanier4() {
        return (Long) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Long, BigDecimal, Boolean, Long, Long, Long, Long> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Long, BigDecimal, Boolean, Long, Long, Long, Long> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return BpJourney.BP_JOURNEY.ID;
    }

    @Override
    public Field<BigDecimal> field2() {
        return BpJourney.BP_JOURNEY.ALLOCATION_RATIO;
    }

    @Override
    public Field<Boolean> field3() {
        return BpJourney.BP_JOURNEY.ARRANGED;
    }

    @Override
    public Field<Long> field4() {
        return BpJourney.BP_JOURNEY.CONTAINER1;
    }

    @Override
    public Field<Long> field5() {
        return BpJourney.BP_JOURNEY.CONTAINER2;
    }

    @Override
    public Field<Long> field6() {
        return BpJourney.BP_JOURNEY.CONTANIER3;
    }

    @Override
    public Field<Long> field7() {
        return BpJourney.BP_JOURNEY.CONTANIER4;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public BigDecimal component2() {
        return getAllocationRatio();
    }

    @Override
    public Boolean component3() {
        return getArranged();
    }

    @Override
    public Long component4() {
        return getContainer1();
    }

    @Override
    public Long component5() {
        return getContainer2();
    }

    @Override
    public Long component6() {
        return getContanier3();
    }

    @Override
    public Long component7() {
        return getContanier4();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public BigDecimal value2() {
        return getAllocationRatio();
    }

    @Override
    public Boolean value3() {
        return getArranged();
    }

    @Override
    public Long value4() {
        return getContainer1();
    }

    @Override
    public Long value5() {
        return getContainer2();
    }

    @Override
    public Long value6() {
        return getContanier3();
    }

    @Override
    public Long value7() {
        return getContanier4();
    }

    @Override
    public BpJourneyRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public BpJourneyRecord value2(BigDecimal value) {
        setAllocationRatio(value);
        return this;
    }

    @Override
    public BpJourneyRecord value3(Boolean value) {
        setArranged(value);
        return this;
    }

    @Override
    public BpJourneyRecord value4(Long value) {
        setContainer1(value);
        return this;
    }

    @Override
    public BpJourneyRecord value5(Long value) {
        setContainer2(value);
        return this;
    }

    @Override
    public BpJourneyRecord value6(Long value) {
        setContanier3(value);
        return this;
    }

    @Override
    public BpJourneyRecord value7(Long value) {
        setContanier4(value);
        return this;
    }

    @Override
    public BpJourneyRecord values(Long value1, BigDecimal value2, Boolean value3, Long value4, Long value5, Long value6, Long value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BpJourneyRecord
     */
    public BpJourneyRecord() {
        super(BpJourney.BP_JOURNEY);
    }

    /**
     * Create a detached, initialised BpJourneyRecord
     */
    public BpJourneyRecord(Long id, BigDecimal allocationRatio, Boolean arranged, Long container1, Long container2, Long contanier3, Long contanier4) {
        super(BpJourney.BP_JOURNEY);

        setId(id);
        setAllocationRatio(allocationRatio);
        setArranged(arranged);
        setContainer1(container1);
        setContainer2(container2);
        setContanier3(contanier3);
        setContanier4(contanier4);
    }
}
