/*
 * This file is generated by jOOQ.
 */
package com.restapi.jooq.model.tables.records;


import com.restapi.jooq.model.tables.BpOrderLine;

import java.math.BigDecimal;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BpOrderLineRecord extends UpdatableRecordImpl<BpOrderLineRecord> implements Record5<Long, Long, BigDecimal, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.bp_order_line.id</code>.
     */
    public BpOrderLineRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.bp_order_line.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.bp_order_line.order_id</code>.
     */
    public BpOrderLineRecord setOrderId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.bp_order_line.order_id</code>.
     */
    public Long getOrderId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.bp_order_line.weight</code>.
     */
    public BpOrderLineRecord setWeight(BigDecimal value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.bp_order_line.weight</code>.
     */
    public BigDecimal getWeight() {
        return (BigDecimal) get(2);
    }

    /**
     * Setter for <code>public.bp_order_line.source</code>.
     */
    public BpOrderLineRecord setSource(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.bp_order_line.source</code>.
     */
    public String getSource() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.bp_order_line.destination</code>.
     */
    public BpOrderLineRecord setDestination(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.bp_order_line.destination</code>.
     */
    public String getDestination() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, Long, BigDecimal, String, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Long, Long, BigDecimal, String, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return BpOrderLine.BP_ORDER_LINE.ID;
    }

    @Override
    public Field<Long> field2() {
        return BpOrderLine.BP_ORDER_LINE.ORDER_ID;
    }

    @Override
    public Field<BigDecimal> field3() {
        return BpOrderLine.BP_ORDER_LINE.WEIGHT;
    }

    @Override
    public Field<String> field4() {
        return BpOrderLine.BP_ORDER_LINE.SOURCE;
    }

    @Override
    public Field<String> field5() {
        return BpOrderLine.BP_ORDER_LINE.DESTINATION;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getOrderId();
    }

    @Override
    public BigDecimal component3() {
        return getWeight();
    }

    @Override
    public String component4() {
        return getSource();
    }

    @Override
    public String component5() {
        return getDestination();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getOrderId();
    }

    @Override
    public BigDecimal value3() {
        return getWeight();
    }

    @Override
    public String value4() {
        return getSource();
    }

    @Override
    public String value5() {
        return getDestination();
    }

    @Override
    public BpOrderLineRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public BpOrderLineRecord value2(Long value) {
        setOrderId(value);
        return this;
    }

    @Override
    public BpOrderLineRecord value3(BigDecimal value) {
        setWeight(value);
        return this;
    }

    @Override
    public BpOrderLineRecord value4(String value) {
        setSource(value);
        return this;
    }

    @Override
    public BpOrderLineRecord value5(String value) {
        setDestination(value);
        return this;
    }

    @Override
    public BpOrderLineRecord values(Long value1, Long value2, BigDecimal value3, String value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BpOrderLineRecord
     */
    public BpOrderLineRecord() {
        super(BpOrderLine.BP_ORDER_LINE);
    }

    /**
     * Create a detached, initialised BpOrderLineRecord
     */
    public BpOrderLineRecord(Long id, Long orderId, BigDecimal weight, String source, String destination) {
        super(BpOrderLine.BP_ORDER_LINE);

        setId(id);
        setOrderId(orderId);
        setWeight(weight);
        setSource(source);
        setDestination(destination);
    }
}
