/*
 * This file is generated by jOOQ.
 */
package com.restapi.jooq.model.tables;


import com.restapi.jooq.model.Keys;
import com.restapi.jooq.model.Public;
import com.restapi.jooq.model.tables.records.BpOrderRecord;

import java.math.BigDecimal;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BpOrder extends TableImpl<BpOrderRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.bp_order</code>
     */
    public static final BpOrder BP_ORDER = new BpOrder();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BpOrderRecord> getRecordType() {
        return BpOrderRecord.class;
    }

    /**
     * The column <code>public.bp_order.id</code>.
     */
    public final TableField<BpOrderRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.bp_order.weight</code>.
     */
    public final TableField<BpOrderRecord, BigDecimal> WEIGHT = createField(DSL.name("weight"), SQLDataType.NUMERIC(22, 10), this, "");

    private BpOrder(Name alias, Table<BpOrderRecord> aliased) {
        this(alias, aliased, null);
    }

    private BpOrder(Name alias, Table<BpOrderRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.bp_order</code> table reference
     */
    public BpOrder(String alias) {
        this(DSL.name(alias), BP_ORDER);
    }

    /**
     * Create an aliased <code>public.bp_order</code> table reference
     */
    public BpOrder(Name alias) {
        this(alias, BP_ORDER);
    }

    /**
     * Create a <code>public.bp_order</code> table reference
     */
    public BpOrder() {
        this(DSL.name("bp_order"), null);
    }

    public <O extends Record> BpOrder(Table<O> child, ForeignKey<O, BpOrderRecord> key) {
        super(child, key, BP_ORDER);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public Identity<BpOrderRecord, Long> getIdentity() {
        return (Identity<BpOrderRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<BpOrderRecord> getPrimaryKey() {
        return Keys.PK_BP_ORDER;
    }

    @Override
    public List<UniqueKey<BpOrderRecord>> getKeys() {
        return Arrays.<UniqueKey<BpOrderRecord>>asList(Keys.PK_BP_ORDER);
    }

    @Override
    public BpOrder as(String alias) {
        return new BpOrder(DSL.name(alias), this);
    }

    @Override
    public BpOrder as(Name alias) {
        return new BpOrder(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public BpOrder rename(String name) {
        return new BpOrder(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public BpOrder rename(Name name) {
        return new BpOrder(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Long, BigDecimal> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
